# Generated by Django 6.0.2 on 2026-02-12 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=250)),
                ('dateTimeOfCreation', models.DateField()),
                ('userId', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', models.CharField()),
                ('dateTimeOfCreation', models.DateField()),
                ('userId', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Discussion.comment')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='Discussion.discussion')),
            ],
        ),
    ]
