# Generated by Django 6.0.2 on 2026-02-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dateTimeOfCreation',
            new_name='creationDate',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='dateTimeOfCreation',
            new_name='creationDate',
        ),
    ]
