# Generated by Django 6.0.2 on 2026-02-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='dateTimeOfCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
