# Generated by Django 6.0.2 on 2026-02-15 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0002_alter_discussion_datetimeofcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateTimeOfCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Discussion.comment'),
        ),
    ]
